POST http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFoaW4iLCJlbWFpbCI6Im1AYS5jb20iLCJpZCI6IjY0NWIyYTY1NjYzZjNiZTc0MWU4MTU4YyIsImlhdCI6MTY4Mzg2ODU1OX0.iSnH2nizMUBJbCC_WvNx0UWbhT1unPdm_u_GSlr64aY 

{
    "name": "Nayeem",
    "age": "14"
} 


###
PUT http://localhost:3000/users/645b2a4d663f3be741e8158a HTTP/1.1
content-type: application/json

{
    "title": "Mahin",
    "age": "16"
} 

###

get http://localhost:3000/users HTTP/1.1
Authorization: mytoken xxx

###

get http://localhost:3000/users/645b2a4d663f3be741e8158a HTTP/1.1


###

delete http://localhost:3000/users/645b15225a1688767b32cae4 HTTP/1.1