POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "areeba",
    "age": "10"
} 

###
PUT http://localhost:3000/users/2 HTTP/1.1
content-type: application/json

{
    "title": "Tamim",
    "age": "13"
} 

###

get http://localhost:3000/users HTTP/1.1


###

get http://localhost:3000/users/1 HTTP/1.1


###

delete http://localhost:3000/users/3 HTTP/1.1