POST http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: mytoken xxx 

{
    "name": "Nayeem",
    "age": "14"
} 

###
PUT http://localhost:3000/users/645b2a4d663f3be741e8158a HTTP/1.1
content-type: application/json

{
    "title": "Mahin",
    "age": "16"
} 

###

get http://localhost:3000/users HTTP/1.1
Authorization: mytoken xxx

###

get http://localhost:3000/users/645b2a4d663f3be741e8158a HTTP/1.1


###

delete http://localhost:3000/users/645b15225a1688767b32cae4 HTTP/1.1